# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 257f84fdaeb73703cf3bea2ffb9cf2f4871e4fc6455be85c04ddcb4ce4696177d76efa96ac66debb316b4365fee53720c30545e424ccac3c786edc6c3514946b

test:
  secret_key_base: 61cedcd35bea0ebe7a3566de78ae367ee7a55089666de4c9b0648b9df9cc5f71b77d0c2db14f30eeba0bebdd45c1806a83ab0f199b04254b56d7c0bda81cc805

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
